export const GET_GENRES = 'GET_GENRES';
export const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
export const GET_GENRES_FAILURE = 'GET_GENRES_FAILURE';

export const GENRE_LOAD = 'GENRE_LOAD';

// export const GET_DATE = 'GET_DATE';
// export const GET_DATE_SUCCESS = 'GET_DATE_SUCCESS';
// export const GET_DATE_FAILURE = 'GET_DATE_FAILURE';

export const GET_RATING = 'GET_RATING';
export const GET_RATING_SUCCESS = 'GET_RATING_SUCCESS';
export const GET_RATING_FAILURE = 'GET_RATING_FAILURE';

export const GET_PG_CONTENT = 'GET_PG_CONTENT';
export const GET_PG_CONTENT_SUCCESS = 'GET_PG_CONTENT_SUCCESS';
export const GET_PG_CONTENT_FAILURE = 'GET_PG_CONTENT_FAILURE';

export const GET_SEARCH_TXT = 'GET_SEARCH_TXT';

export const SEARCH_TYPE = 'SEARCH_TYPE';

export const SEARCH_TITLE = 'SEARCH_TITLE';
export const GET_SEARCH_TITLE_SUCCESS = 'GET_SEARCH_TITLE_SUCCESS';
export const GET_SEARCH_TITLE_FAILURE = 'GET_SEARCH_TITLE_FAILURE';

export const SEARCH_AUTH = 'SEARCH_AUTH';

export const SEARCH_LOAD = 'SEARCH_LOAD';

export const DATE_CHANGE = 'DATE_CHANGE';

export const CHANGE_WEEK = 'CHANGE_WEEK';

export const UPDATE_CONTENT_DATE = 'UPDATE_CONTENT_DATE';
export const UPDATE_CONTENT_DATE_SUCCESS = 'UPDATE_CONTENT_DATE_SUCCESS';
export const UPDATE_CONTENT_DATE_FAILURE = 'UPDATE_CONTENT_DATE_FAILURE';

export const GET_HOME_CONTENT = 'GET_HOME_CONTENT';
export const GET_HOME_CONTENT_SUCCESS = 'GET_HOME_CONTENT_SUCCESS';
export const GET_HOME_CONTENT_FAILURE = 'GET_HOME_CONTENT_FAILURE';

export const GET_NEW_GENRE = 'GET_NEW_GENRE';
export const GET_NEW_GENRE_SUCCESS = 'GET_NEW_GENRE_SUCCESS';
export const GET_NEW_GENRE_FAILURE = 'GET_NEW_GENRE_FAILURE';

export const SET_GENRE_DATES = 'SET_GENRE_DATES';

export const DETAIL_BK_VIEW = 'DETAIL_BK_VIEW';

export const DETAIL_LOAD = 'DETAIL_LOAD';

export const NO_DATA = 'NO_DATA';

export const IS_LOADING = 'IS_LOADING';